routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Route::resource('users', UserController::class);

Route::get('restore/{id}', [UserController::class, 'restore'])->name('restore');

Route::get('get-users', [UserController::class, 'getUsers'])->name('get-users');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'last_name',
        'email',
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    protected $with = ['courses', 'details'];

    public function getData()
    {
        return static::orderBy('created_at', 'desc')->get();
    }

    public function courses()
    {
        return $this->hasMany(UsersSubject::class);
    }

    public function details()
    {
        return $this->hasOne(UsersDetail::class);
    }

    public function getFullNameAttribute()
    {
        return ucwords($this->name).' '.ucwords($this->last_name);
    }
}

app/Models/UsersDetail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UsersDetail extends Model
{
    use HasFactory;
}

app/Models/UsersSubject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UsersSubject extends Model
{
    use HasFactory;

    protected $table = "school_subjects";
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use DataTables;

class UserController extends Controller
{
    public function index()
    {
        return view('users');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|unique:users',
            'username' => 'required|unique:users',
            'password' => 'required|string|min:8',
        ]);

        User::create($request->all());

        return redirect()->back()->with(['success' => 'true', 'title' => 'Excelente', 'text' => 'El usuario ha sido creado con exito']);
    }

    public function show($id)
    {
        $user = User::withTrashed()->whereId($id)->first();
        return view('user', compact('user'));
    }

    public function edit(User $user)
    {
        return response()->json(["user" => $user]);
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email',
            'username' => 'required',
            'password' => 'required|string|min:8',
        ]);

        $user->update($request->all());

        return redirect()->back()->with(['success' => 'true', 'title' => 'Excelente', 'text' => 'El usuario ha sido actualizado con exito']);
    }

    public function destroy (Request $request, User $user)
    {
        if ($request->ajax()) {
            $user->delete();
            $users = User::orderBy('id', 'DESC')->paginate(5);

            return response()->json(["users" => $users]);
        }
    }

    public function restore($id)
    {
        $user = User::withTrashed()
            ->whereId($id)
            ->firstOrFail();
        $user->restore();

        return redirect()->back();
    }

    public function getUsers(Request $request, User $user)
    {
        $data = $user->getData();
        return \DataTables::of($data)
            ->addColumn('Actions', function($data) {
                return "<a class='btn btn-sm btn-primary' href='/users/$data->id}'>Ver</a>
                <button class='btn btn-sm btn-primary' onclick='getUser( $data->id )'>Editar</button>
                <button type='button' class='btn btn-sm btn-danger' onclick='deleteData( $data->id )'>Borrar</button>";
            })
            ->rawColumns(['Actions'])
            ->make(true);
    }
}

resources/views/modal.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="text-center modal-title w-100" id="exampleModalLabel">Registrar un nuevo usuario</h5>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">

                <form class="p-5 rounded-3" method="POST" id="usersModal" action="{{ route('users.store') }}">
                    <input name="_method" id="methodForm" type="hidden" value="POST">
                    @csrf
                    <div class="mb-3 form-floating">
                        <input type="text" class="form-control" placeholder="Nombre" name="name" value="{{ old('name') }}" required>
                        <label for="floatingInput">Nombre</label>
                        @error('name') <span class="text-danger">{{ $message }}</span> @enderror
                    </div>

                    <div class="mb-3 form-floating">
                        <input type="text" class="form-control" placeholder="Apellido" name="last_name" value="{{ old('last_name') }}">
                        <label for="floatingInput">Apellido</label>
                        @error('last_name') <span class="text-danger">{{ $message }}</span> @enderror
                    </div>

                    <div class="mb-3 form-floating">
                    <input type="email" class="form-control" placeholder="name@example.com" name="email" value="{{ old('email') }}" required>
                    <label for="floatingInput">Email</label>
                        @error('email') <span class="text-danger">{{ $message }}</span> @enderror
                    </div>

                    <div class="mb-3 form-floating">
                        <input type="text" class="form-control" placeholder="Username" name="username" value="{{ old('username') }}" required>
                        <label for="floatingInput">Nombre de usuario</label>
                        @error('username') <span class="text-danger">{{ $message }}</span> @enderror
                    </div>

                    <div class="mb-3 form-floating">
                    <input type="password" class="form-control" id="floatingPassword" placeholder="Contraseña" name="password" required>
                    <label for="floatingPassword">Password</label>
                    @error('password') <span class="text-danger">{{ $message }}</span> @enderror
                    </div>

                    <div class="form-floating">
                        <button type="button" class="btn btn-secondary w-100 col-5 btn-md-lg" data-dismiss="modal">Cancelar</button>

                        <button class="float-right w-100 btn btn-primary col-5 btn-md-lg" type="submit">Guardar</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

resources/views/user.blade.php
@extends('welcome')

@section('css')
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
@endsection

@section('content')
    <div class="col-12">
        <h1 class="display-4">Mostrar Usuario</h1>
    </div>

    <div class="p-4 pb-0 shadow-lg pe-lg-0 pt-lg-5 align-items-center rounded-3 col-12">
        <div class="p-3 col p-lg-5 pt-lg-3">
          <h1 class="display-4">{{ $user->full_name }}</h1>

            <p class="lead">
                estatus:
                <span class="text-muted">{{ $user->deleted_at ? 'inactivo' : 'activo' }}</span>
            </p>

            <p class="lead">
                email:
                <span class="text-muted"> {{ $user->email }} </span>
            </p>

            <p class="lead">
                nombre de usuario:
                <span class="text-muted">{{ $user->username }}</span>
            </p>

            <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                      Informacion de la escuela
                    </button>
                  </h2>

                  <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        @if($user->details)
                            <p class="lead">
                                Grupo:
                                <span class="text-muted">{{ $user->details->group }}</span>
                            </p>

                            <p class="lead">
                                Grado:
                                <span class="text-muted">{{ $user->details->grade }}</span>
                            </p>
                        @else
                        No hay informacion que mostrar
                        @endif
                    </div>
                  </div>
                </div>

                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                      Materias cursadas
                    </button>
                  </h2>

                  <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        @forelse($user->courses ?: [] as $course)
                        <p class="lead">
                            Materia:
                            <span class="text-muted">{{ $course->name }}</span>
                        </p>
                        @empty
                        No hay informacion que mostrar
                        @endforelse
                    </div>
                  </div>
                </div>
              </div>

              @if($user->deleted_at)
              <a href="{{ route('restore', $user->id) }}" class="float-right btn btn-primary">Activar usuario</a>
              @endif

        </div>
      </div>
@endsection

@section('js')
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
@endsection

resources/views/users.blade.php
@extends('welcome')

@section('css')
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
@endsection

@section('content')
    <div class="mb-4 col col-md-3">
        <button type="button" class="btn btn-primary btn-lg" id="btnUser" data-toggle="modal" data-target="#exampleModal">
            Crear nuevo usuario
        </button>
    </div>

    <div class="col-12">
        <h3>Lista de usuarios</h3>

        <div class="table-responsive">
            <table class="table table-bordered datatable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                        <th width="150" class="text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody id="users">
                </tbody>
            </table>
        </div>
    </div>

    @include('modal')

    @endsection

    @section('js')
    {{-- <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> --}}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    {{-- <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> --}}

    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function() {
            $.noConflict();
            var dataTable = $('.datatable').DataTable({
                processing: true,
                serverSide: true,
                autoWidth: true,
                pageLength: 5,
                // scrollX: true,
                "order": [[ 0, "desc" ]],
                ajax: '{{ route('get-users') }}',
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'last_name', name: 'last_name'},
                    {data: 'email', name: 'email'},
                    {data: 'Actions', name: 'Actions', orderable:false, serachable:false, sClass:'text-center'},
                ]
            });
        });

        async function getUser(id) {
            var url = `/users/${id}/edit`

            axios.get(url)
            .then(response => {
                document.getElementById('btnUser').click();

                $("#usersModal").attr('action', `/users/${id}` )
                $("#methodForm").attr('value', `PUT`)

                $('input[name=name]').val(response.data.user.name)
                $('input[name=last_name]').val(response.data.user.last_name)
                $('input[name=email]').val(response.data.user.email)
                $('input[name=username]').val(response.data.user.username)
            }).catch(e => {
                console.log(e);
            });
        }

        async function deleteData(id) {
            var url = `/users/${id}`

            axios.delete(url, {
                user: id,
            }).then(response => {
                const table = $("#users").empty();

                $.each(response.data.users.data, function(key, value) {
                  table.append(`
                  <tr>
                        <th scope="row">${ value.id }</th>
                        <td>${ value.name }</td>
                        <td>${ value.last_name }</td>
                        <td>${ value.email }</td>
                        <td>
                            <a class='btn btn-sm btn-primary' href='/users/${value.id}'>Ver</a>
                            <button class='btn btn-sm btn-primary' onclick='getUser( ${value.id} )'>Editar</button>
                            <button type="button" class="btn btn-sm btn-danger" onclick="deleteData(${ value.id })">Borrar</button>
                        </td>
                    </tr>
                  `)
                })

                Swal.fire({
                    title: 'Excelente',
                    text: 'El usuario ha sido eliminado correctamente',
                    icon: 'success',
                    timer: '1500'
                })

            }).catch(e => {
                console.log(e);
            });
        }

        @if( $errors->any() )
            $(document).ready(() => {
                document.getElementById('btnUser').click();
            });
        @endif
    </script>
@endsection